// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCibYnZ0EQr32h4Bh6XfIjMCDDxjEyS1uI',
    appId: '1:1057067121632:web:c287050b9628cf342cc985',
    messagingSenderId: '1057067121632',
    projectId: 'pushnotification-38002',
    authDomain: 'pushnotification-38002.firebaseapp.com',
    storageBucket: 'pushnotification-38002.firebasestorage.app',
    measurementId: 'G-JFXQPW799R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB4fyGFfYKE2mhuT3znXrh-j1KvabVTc',
    appId: '1:1057067121632:android:bfd06f55f2a6bf522cc985',
    messagingSenderId: '1057067121632',
    projectId: 'pushnotification-38002',
    storageBucket: 'pushnotification-38002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qAhCOHCWP91XbpV3RJKQRVvTs9fjJMc',
    appId: '1:1057067121632:ios:afc63803e2da8e252cc985',
    messagingSenderId: '1057067121632',
    projectId: 'pushnotification-38002',
    storageBucket: 'pushnotification-38002.firebasestorage.app',
    iosBundleId: 'com.junaid.flutterPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7qAhCOHCWP91XbpV3RJKQRVvTs9fjJMc',
    appId: '1:1057067121632:ios:afc63803e2da8e252cc985',
    messagingSenderId: '1057067121632',
    projectId: 'pushnotification-38002',
    storageBucket: 'pushnotification-38002.firebasestorage.app',
    iosBundleId: 'com.junaid.flutterPushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCibYnZ0EQr32h4Bh6XfIjMCDDxjEyS1uI',
    appId: '1:1057067121632:web:61890d46a41e698d2cc985',
    messagingSenderId: '1057067121632',
    projectId: 'pushnotification-38002',
    authDomain: 'pushnotification-38002.firebaseapp.com',
    storageBucket: 'pushnotification-38002.firebasestorage.app',
    measurementId: 'G-CHSK0B2C3G',
  );

}